### ISSUE TITLE
Question on github-resource-converter

### ISSUE THREAD

**Issue by gregswindle** [gregswindle/github-resource-converter#10]
> **Note:** this issue was sent to my (@gregswindle) personal email address. 
> I have copied and pasted the email body, but left the sender anonymous.

## 1. User story summary

> ⌦ Describe what you want to accomplish {do something},
> ⌦ in what role/capacity {role},
> ⌦ and why it's important to you {achieve value}.

As a user,
I want to export GitHub issues
In order to review them.

## 🐞 2. Steps to reproduce (for defects only)

* > ⌦ Provide a link to a live example, or
* > ⌦ Replace the examples below with an unambiguous sequence of
  > ⌦ instructions that end with proof of the defect.
* > ⌦ Include source code and log files, if relevant and available.

1. Updated Nodejs via Homebrew (had some issues with some symlinks, but finally got a successful update)
2. Cloned Repo
3. Installed via npm i -g github-resource-converter  inside MAC terminal
4. Created the personal access token inside Github and ran this… 

   ```bash
   mkdir -p /usr/local/etc/github-resource-center/envvars/
   touch /usr/local/etc/github-resource-center/envvars/.env
   echo "GITHUB_ACCESS_TOKEN="{your-personal-access-token-value}" > \
   /usr/local/etc/github-resource-center/envvars/.env
   ```

5. Ran this...

   ```bash
    github-resource-converter \
      --owner gregswindle \
      --repo eslint-plugin-crc \
      --dest './docs/gregswindle-eslint-plugin-crc-issues.csv'
   ```

6. I did change all the `—owner` and `--repo` but not the `—dest`  but it’s not even getting that far. It doesn’t even see the command in the `.bashrc` file.
7. bash doesn’t see the command. 

   ```bash
   => github-resource-converter \
   | =>   —owner cj***** \
   | =>   —repo Ku****** \
   | =>   --dest './docs/gregswindle-eslint-plugin-crc-issues.csv'
   -bash: github-resource-converter: command not found
   ```

If you have any insight. I would greatly appreciate your help. 
## 🐞 3. Your environment (for defects only)

* > ⌦ Include as many relevant details about the environment
  > ⌦ in which the defect occured.

- Version of `github-resource-converter`: v1.0.0
- Operating System and version (desktop or mobile): MacOSX 10.3.3
- Link to your project:

**Comment by gregswindle** [comment]
Thanks for reporting!

I uninstalled and reinstalled from npm, and I got the following error (please note the 🚨 emojis are my own):

```bash
npm i -g github-resource-converter
/Users/swindle/.nvm/versions/node/v8.9.4/bin/grc -> /Users/swindle/.nvm/versions/node/v8.9.4/lib/node_modules/github-resource-converter/lib/cli.js

> dtrace-provider@0.8.6 install /Users/swindle/.nvm/versions/node/v8.9.4/lib/node_modules/github-resource-converter/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp
+ github-resource-converter@1.0.0-alpha
added 91 packages from 101 contributors in 10.415s
Gregorys-MBP-2:govinfo-link-js swindle$ grc --version
module.js:540
    throw err;
    ^
🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/swindle/.nvm/versions/node/v8.9.4/lib/node_modules/github-resource-converter/lib/cli.js:5:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
Gregorys-MBP-2:govinfo-link-js swindle$ github-resource-converter
module.js:540
    throw err;
    ^
🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 🚨 
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/swindle/.nvm/versions/node/v8.9.4/lib/node_modules/github-resource-converter/lib/cli.js:5:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```
